### ISSUE TITLE
Speed up make operation

### ISSUE THREAD

**Issue by augustinsangam** [lajoiepy/argos3_docker_example#2]
Make stage when Installing Argos for source is a little bit long. 

Here are statistics (provided by time) for the whole image build operation on my computer :

real    5m55.572s
user    0m0.306s
sys     0m0.190s

Adding **multiple parallel jobs** make the operation twice faster.

You just need to replace the line 48

```bash
make
```
with [this](https://www.gnu.org/software/make/manual/html_node/Options-Summary.html) :
```bash
make -j $(nproc)
```

New statistics :
real    3m15.421s 
user    0m0.262s 
sys     0m0.155s

Thanks for the DockerFIle :wink:

**Comment by lajoiepy** [comment]
True, why not, thanks for the suggestion :) 603a665
